var name1='HP';
var Age= 26;
var isHoliday= true
var isReact= undefined;
var shouldcheck= null;
console.log('name1',name1);
console.log('Age', Age);
console.log('isHoliday',isHoliday);
console.log('isReact',isReact);
console.log('shouldcheck',shouldcheck);
var obj1={};
var obj2= {
           name2 :'Vimal',
           Age :27,
           Designation:'Manager',
           obj3 : {
            company:'HPCL'
           }

}
console.log('obj1', obj1);
console.log('obj2', obj2);
console.log('type of name1',typeof name1);
console.log('type of Age',typeof Age);
console.log('type of isHoliday',typeof isHoliday);

